// <auto-generated>
// Rewired Constants
// This list was generated on 2020/02/13 3:08:51
// The list applies to only the Rewired Input Manager from which it was generated.
// If you use a different Rewired Input Manager, you will have to generate a new list.
// If you make changes to the exported items in the Rewired Input Manager, you will
// need to regenerate this list.
// </auto-generated>

namespace RewiredConsts {
    public static partial class Action {
        // Default
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Horizontal (左右)")]
        public const int Horizontal = 0;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Vertical (前後 上下)")]
        public const int Vertical = 1;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Submit (決定)")]
        public const int Submit = 2;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Cancel (取消)")]
        public const int Cancel = 3;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Attack (攻撃)")]
        public const int Attack = 4;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Jump (跳躍)")]
        public const int Jump = 5;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Dodge (回避)")]
        public const int Dodge = 6;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Special (特殊)")]
        public const int Special = 7;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Wild Release (野生解放)")]
        public const int Wild_Release = 8;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Run (走行)")]
        public const int Run = 9;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Aim (照準)")]
        public const int Aim = 10;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Change Target (照準変更)")]
        public const int Change_Target = 11;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Pause (一時停止)")]
        public const int Pause = 12;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Screen Capture (画面撮影)")]
        public const int Screen_Capture = 13;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Camera Horizontal (カメラ水平移動)")]
        public const int Camera_Horizontal = 14;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Camera Vertical (カメラ垂直移動)")]
        public const int Camera_Vertical = 15;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Camera Control (カメラ操作)")]
        public const int Camera_Control = 16;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Camera Reset (カメラ初期化)")]
        public const int Camera_Reset = 17;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Command Horizontal (指示対象変更)")]
        public const int Command_Horizontal = 22;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Command Vertical (指示内容変更)")]
        public const int Command_Vertical = 23;
        // UI
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "UI", friendlyName = "UIHorizontal")]
        public const int UIHorizontal = 18;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "UI", friendlyName = "UIVertical")]
        public const int UIVertical = 19;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "UI", friendlyName = "UISubmit")]
        public const int UISubmit = 20;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "UI", friendlyName = "UICancel")]
        public const int UICancel = 21;
    }
    public static partial class Category {
        public const int Default = 0;
        public const int UI = 2;
    }
    public static partial class Layout {
        public static partial class Joystick {
            public const int Default = 0;
        }
        public static partial class Keyboard {
            public const int Default = 0;
        }
        public static partial class Mouse {
            public const int Default = 0;
        }
        public static partial class CustomController {
            public const int Default = 0;
        }
    }
    public static partial class Player {
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "System")]
        public const int System = 9999999;
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "Player0")]
        public const int Player0 = 0;
    }
    public static partial class CustomController {
    }
    public static partial class LayoutManagerRuleSet {
    }
    public static partial class MapEnablerRuleSet {
    }
}
